
#FROM gw000/keras-full:latest
FROM gw000/keras:2.0.2-py2-tf-gpu

RUN apt-get update -qq \
 && apt-get install --no-install-recommends -y \
 openssh-server \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
 
 
 EXPOSE 22

